### ISSUE TITLE
[Question] Is this a workaround for Wix "browser not supported" on ios16 / ios16.7?

### ISSUE THREAD

**Issue by Amousey** [katagaki/Unagent#16]
### Question 
Does this work for viewing (not editing) **Wix** websites - which all now give "browser is no longer supported" errors on ios16 / ios16.7 (safari 16.6) - which is the final update for some iPhone models - the same phones work fine on Firefox even though it uses the same underlying webkit.

Any wix website could test this e.g. [this link](https://www.wix.com/blog/wix-websites-examples).

### Javascript?
The only review mentions that "it's not going to stop javascript" so I'm confused about if this means that javascript checking for browser version will work (I can't think of a different way to check browser version)

### Refund policy / suggestion 
If this is not supported can a refund be claimed? Is would be helpful to add this info to the app description. Alternatively a very short free trial version would be appreciated.

**Comment by katagaki** [comment]
Hi @Amousey 

Regarding 'browser no longer supported' messages, they can be generated based on some factors, including the user agent. A website might check whether features (web APIs) are available in a browser, for instance.
As I don't have a device running iOS 16, you might want to use a website like [this](https://www.whatsmyua.info) to see if Unagent is correctly changing the user agent in Safari.

About the JavaScript review, it is absolutely correct to say that websites may use advanced fingerprinting or browser identification scripts to determine (with some level of accuracy) what browser is actually being used. [WhatIsMyBrowser.com](https://whatismybrowser.com/) uses a similar technique, which you might see when going to its website while the user agent is changed.
This is not something I can control or override easily.

If you would like a refund, you can visit [reportaproblem.apple.com](https://reportaproblem.apple.com) to request for one.
