### ISSUE TITLE
nothing happens

### ISSUE THREAD

**Issue by svnv-svsv-jm** [katagaki/Unagent#24]
On Safari, i visit a website then tap on A then Unagent and nothing happens. Just paid for nothing. Reporting.

**Comment by katagaki** [comment]
Hi @svnv-svsv-jm 

Please note that all settings for Unagent (including the global user agent and per site user agent settings) are located within the app.

If you are unsatisfied with your purchase, you can request for a refund [here](https://reportaproblem.apple.com).
